### ISSUE TITLE
Convert deployment to use webpack

### ISSUE THREAD

**Issue by berkus** [FreeFeed/freefeed-react-client#1]
We use requirejs/gulp but could try using webpack as deployment mechanism.

**Comment by clbn** [comment]
What is the reasoning behind switching from gulp to webpack?

**Comment by berkus** [comment]
Guys say it will be more convenient.

**Comment by clbn** [comment]
Excuse me, I don't have any strong opinion neither on Gulp nor on Webpack, and I don't want to look like I'm just nitpicking, but don't we need a little more objective reasons for the change?
