### ISSUE TITLE
Error when opening https://freefeed.net/friends via direct link

### ISSUE THREAD

**Issue by davidmz** [FreeFeed/freefeed-react-client#1033]
An error occurs when opening https://freefeed.net/friends via a direct link. If you open this page via a link from other FreeFeed pages, it opens normally.

![image](https://user-images.githubusercontent.com/132120/65718111-8c563480-e0ab-11e9-8299-9f582af90281.png)

**Comment by ghost** [comment]
is this on live? current state:
![Screenshot_2019-10-09 FreeFeed](https://user-images.githubusercontent.com/39516339/66440049-f1a61000-ea31-11e9-9604-ccdf57a26cc9.png)
