### ISSUE TITLE
Links in comments to images uploaded to FreeFeed should open in PhotoSwipe

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#1060]
Links in comments which look like links to images uploaded to FreeFeed should be opened in PhotoSwipe

Thumbnail image-links should be converted to full image-links.

we might need to expose image-url prefixes via API for this.

This should work for extensions supported by PhotoSwipe (jpg, png, gif, …?)

Cmd/Ctrl-click and Middle-click should open image in new tab directly (as it works for regular post-attachments)

**Comment by davidmz** [comment]
I think we shouldn't limit ourselves to our own pictures. It is natural for the user to expect that any link ended by ".jpg" should be opened in a lightbox.

In this case, there is no point in doing separate support on the server. The client should know how to show different links (for example, we can show preview for the link to Instagram _page_).

Also it must be some indication for such links. Example from Mokum:

![image](https://user-images.githubusercontent.com/132120/70611524-62c29900-1c16-11ea-9348-a2a4642663f0.png)

**Comment by indeyets** [comment]
I was thinking about one bite at a time approach. Start with something obvious and proceed to different cases later. 

Server support for attachments might also give us better UX (such as showing previews optimized for lightbox, once we have those)

**Comment by davidmz** [comment]
Seems fixed:)
