### ISSUE TITLE
URL-autoparser greps only 2-letter "TLDs"

### ISSUE THREAD

**Issue by ghost** [FreeFeed/freefeed-react-client#1073]
current state -- only raw text, no `http[s]://` prefixes:
`test.local test.dev test.js test.ts test.land`

![url-autoparser test](https://user-images.githubusercontent.com/59403389/71643970-17555500-2cc1-11ea-8daf-3d3738f0eb68.png)

( https://freefeed.net/code/224694bd-36f2-45af-ac3c-7d64030fac8b )

**Comment by davidmz** [comment]
What exactly is the problem and how should it work?

**Comment by ghost** [comment]
the problem is _any_ word with 2-letter `.TLD` will be auto-parsed as URL, which includes most commonly `.js` names of javascript-related projects
while actual existing `.gTLD`s like `.dev` or `.land` are not recordnised as URL

there are two main directions for this:
1. autoparse only [existing (g)TLDs](https://data.iana.org/TLD/tlds-alpha-by-domain.txt)
2. get rid of autoparsing of URL all together, since URL-looking text w/o `http(s)://` is likely not actually an URL

**Comment by davidmz** [comment]
mail.ru or freefeed.net are definitely URLs even without schemas.

We should think, whether we want to include an extra 10 kb of TLD list for this feature only. Maybe there exists some list of the most popular TLDs?

**Comment by ghost** [comment]
is there a statistic on how many `.js` there are in posts vs raw `.ru` and `.net` w/o protocol?

**Comment by davidmz** [comment]
For information:
* http://s3.amazonaws.com/alexa-static/top-1m.csv.zip — pretty actual TOP 1M sites from Alexa
* http://s3-us-west-1.amazonaws.com/umbrella-static/index.html — TOP sites AND TLDs from Cisco/OpenDNS

We can use these list to extracn N most popular TLDs
