### ISSUE TITLE
Add custom FF link highlighter instead of default linkify

### ISSUE THREAD

**Issue by berkus** [FreeFeed/freefeed-react-client#109]
Lets use https://github.com/davidmz/ff-url-finder for properly highlighting links and usernames.

**Comment by berkus** [comment]
Can be npm'd from https://www.npmjs.com/package/ff-url-finder

**Comment by davidmz** [comment]
Usage in BetterFeed: https://github.com/davidmz/BetterFeed/blob/master/src%2Fjs%2Futils%2Flinkify.js

**Comment by ujenjt** [comment]
@davidmz Also, maybe it would be helpful to include linkingBeauty logic into ff-url-finder?

**Comment by davidmz** [comment]
@ujenjt done: https://github.com/davidmz/ff-url-finder/commit/0f2e323c9dcdff0b9cea527de7e7856da9b36b12
