### ISSUE TITLE
No reaction on clicking FreeFeed logo

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#110]
Steps to reproduce:

- Authenticated user opens the root page (https://beta.freefeed.net).
- User click FreeFeed logo in the page header.

Expected:

- Force page refresh.
- Visual feedback (ketchup and mustard dance, while page is refreshing).

Actual:

- Nothing happens.

**Comment by dreikanter** [comment]
Side note: I'll be using #diff label for issues related to difference between current production version and react beta.

**Comment by dreikanter** [comment]
Probably related to #83

**Comment by clbn** [comment]
Fixed in #295.
