### ISSUE TITLE
Display names are not displayed

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#111]
Display names are not displayed.

Sample post on production:

![Alt text](https://monosnap.com/file/zDEUdPNSHwA278yDjdImEOg2wy0RRT.png)

Same post on beta:

![Alt text](https://monosnap.com/file/EFWjHdfKmg71eElEkMBSBszfNmaaCJ.png)

* [x] show screenname by default
* [x] option to switch between username, screenname and screenname+username
* [x] show "You" instead of user's own name (independent of selected option)

**Comment by berkus** [comment]
We have this UserName component but need to enable a setting for it and copy options from BetterFeed (only username, only displayname, combined username+displayname), also "Show *You*"

**Comment by clbn** [comment]
Implemented in #286.
