### ISSUE TITLE
"Add comment" link not present

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#112]
There is an "Add comment" link in the end of each thread on production. Beta doesn't have it.

![Alt text](https://monosnap.com/file/sktiMxqUyEXlDaigXxj377vREKTQS0.png)

**Comment by berkus** [comment]
It's actually not any thread, but a thread which has more than 2 comments - see https://github.com/clbn/freefeed-react-client/commit/8838923b3206bffc8241e32b094cc3d9e75a353e#diff-a92ddf38b498ff2d3c4a3ef4b5c4bbc4R23

So I consider this "by design".

**Comment by clbn** [comment]
The present implementation is in agreement with the Old FriendFeed behaviour and the discussion in wg-featureset.
