### ISSUE TITLE
"Sign out" doesn't actually terminate the session

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#114]
Steps to reproduce:

- Authenticated user clicks "sign out" link on the sidebar.

Expected behavior:

- User redirected to `/login` page.
- Session is terminated.

Actual behavior:

- Session is not terminated (it is still possible to see this on the root page).

**Comment by berkus** [comment]
Wait, wat.

**Comment by dreikanter** [comment]
Yup. Just checked again.

**Comment by berkus** [comment]
I'm not following. You're expecting sign out to NOT terminate the session. But it actually terminates the session - that's what sign outs do!

**Comment by berkus** [comment]
My observed behavior:
- press "sign out"
- user is signed out
- redirected to "/login"
- if you try to open any other url user is redirected to "/login"

**Comment by dreikanter** [comment]
Fixed :) Miss the Actual and Expected.

**Comment by berkus** [comment]
Can you also add OS and browser?

**Comment by dreikanter** [comment]
OS X, Chrome (latest, stable).

**Comment by dreikanter** [comment]
It works fine in Safari.

**Comment by berkus** [comment]
Can't reproduce in OSX Chrome Version 47.0.2526.73 (64-bit)

**Comment by dreikanter** [comment]
Mine is 46.0.2490.86 (64-bit) Autoupdate didn't updated it for some reason.
I'll try to upgrade and see if it will help.

**Comment by dreikanter** [comment]
Updated to 47.0.2526.73 (64-bit). Same thing:

![](http://g.recordit.co/48tX6xVImd.gif)

**Comment by berkus** [comment]
Case investigated:
Root domain cookie @`.freefeed.net` spills into beta as it actually SHOULD.

Solution: rename beta cookie.
