### ISSUE TITLE
Ctrl+Click on logo changes current page

### ISSUE THREAD

**Issue by kukutz** [FreeFeed/freefeed-react-client#1154]
1. Any desktop OS, any chromium browser
2. react frontend or freefeed.net
3. go to some non-main page, for example, https://freefeed.net/?offset=60, then ctrl+click on freefeed logo
4. I expect current page remains intact and main page will open in new tab
5. Actually main page will open in new tab AND in the current tab will show posts from main page, BUT URL and navigation links will be from non-main page (i.e. ?offset=60).

**Comment by kukutz** [comment]
I think this problem will reproduce with Ctrl+Click on other links.

**Comment by indeyets** [comment]
Clarification: The bug is strictly about offsets. There are no problems if user starts from page of post or settings
