### ISSUE TITLE
"Friends" menu should be rearranged

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#1158]
![FreeFeed 2020-06-06 13-57-50](https://user-images.githubusercontent.com/13445/83942972-1345da00-a801-11ea-9ea1-d93785aca25d.jpg)

"Browse/edit friends and lists" link is related to "Home" and other lists, but is not really related to other items of the menu. It should be moved closer to them. 

"Direct messages", "My discussions" should be shown after it

**Comment by davidmz** [comment]
Не уверен, что это правильно. Если у юзера нет дополнительных списков, то Browse/edit придётся ставить прямо под Home?

Собственно, и до списков этот пункт относился к Home, но находился внизу и никого это не смущало.

**Comment by indeyets** [comment]
Разница именно в том, что раньше это был ТОЛЬКО Home, а теперь списков может быть много. И возможность редактирования должна быть позиционирована рядом с, собственно, списками.

Кроме того, это сразу же является и рекламой новой функциональности

**Comment by dsumin** [comment]
Я не очень понимаю, куда это уносить? Исторически было внизу секции Friends

**Comment by davidmz** [comment]
Мне это всё ещё не нравится. Мы разбиваем однородное меню пунктом, который отличается шрифтом, длиной, да и нужен редко. Home. Directs, ... — это списки, они для чтения, и их группировка имеет смысл. Browse/edit — это не чтение, а управление. И он исторически сидит отдельно.

В старом фидике это вообще было так:
![image](https://user-images.githubusercontent.com/132120/83943710-ebf20b80-a806-11ea-8702-f753ebf6860d.png)

А для рекламы достаточно бейджика NEW около Browse/edit (а у поиска его пора убрать).

**Comment by indeyets** [comment]
В «старом фидике» логика прослеживается, т.к. элемент управления привязан к доп.спискам. У нас сейчас ситуация хуже.

У меня есть ощущение, что можно сделать даже лучше чем было в «старом фидике», но если сделать как в старом, то этот баг уже можно будет закрыть. Я постараюсь сегодня «нарисовать» как можно сделать ещё лучше (пока что подбегаю к компьютеру не достаточно надолго чтобы успеть)

**Comment by dsumin** [comment]
Придумал свой вариант, завтра выложу.
