### ISSUE TITLE
Don't show irrelevant pagination links

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#116]
Expected behavior:
- "Older items" link is available on any page except the last one (if there are actually older items on the next page).

Actual behavior:
- "Older items" link is available on Direct messages page, regardless the fact, that there are 2 messages at all.
- On production:
  - After clicking "Older items" on Direct messages page, the content of the page didn't change. There still 2 messages on `/filter/direct?offset=30`, `/filter/direct?offset=60`, `/filter/direct?offset=120`...
  - After page refresh, page contents became empty if the offset is greater than the number of messages. "Older items" link disappears.

![Alt text](https://monosnap.com/file/eGgeY1A46AMeUUqz0cvTeeL4gXcjoK.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/R3znGi7D)

**Comment by berkus** [comment]
This is backend meta related. Wontfix for now.
