### ISSUE TITLE
There's no obvious way to create a new list

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#1160]
There are 2 ways to create a new list now:

1. Attempt to Subscribe, Chose "Create new list" in a modal (this one is almost good. I'll post separate issues about it)
2. Open "Browse/edit friends…", Click on "View:" (???) control, find "Add friend list" in it

(2) is totally not obvious.

I suggest to:

1. Replace "View" with "Manage list"
2. Add explicit "Create list…" button to the right of selector
3. Remove "Add friend list" from selector

I know that "All subscriptions" is not a list, strictly speaking, but overall this should give user better understanding of how to proceed

**Comment by davidmz** [comment]
Можно сделать как в старом фидике:
![image](https://user-images.githubusercontent.com/132120/83949538-1a82dd00-a82d-11ea-8050-86e2f416f940.png)

**Comment by davidmz** [comment]
Совсем вплотную ставить я пока не очень хочу — ссылка Edit this list появляется только у дополнительных листов, а Add friend list должна быть видна всегда.

**Comment by dsumin** [comment]
@davidmz давай так и сделаем.

**Comment by indeyets** [comment]
Я всё ещё считаю что формулировка "Manage list" правильнее чем "View"
