### ISSUE TITLE
Subscribe-pane on user's page

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#1161]
![Subscription pane](https://user-images.githubusercontent.com/13445/83944167-1ee9ce80-a80a-11ea-89b4-cf6ca2fe3b20.jpg)

Text input for the name of new list is poorly aligned with regular text-names. It would look much better without excessive paddings, border and with a matching font-family/size.

But there's another way which, probably, is even better: Add "Create new list" link/button without checkbox. The click reveals full width text-input in it's place with a "Save" button to the right of it. The click on "Save" shows a new pre-selected item in a list of friend-lists and "Create new list" link/button is displayed below, again (to create more lists).

p.s. "Home" must be checked by default. It's ok if user unchecks it, but default should be sane

**Comment by davidmz** [comment]
Но при этом в промежуточном состоянии у нас будет аж три кнопки в таком маленьком попапе (а по уму так все четыре надо, по одному Cancel на форму):
```
[ ] Home
[ ] с картинками
[________________] [ Save ]
[ Subscribe ] [ Cancel ]
```

**Comment by indeyets** [comment]
Looks like it was fixed a long time ago
