### ISSUE TITLE
Feed selector and user info not working right after sign-in

### ISSUE THREAD

**Issue by davidmz** [FreeFeed/freefeed-react-client#138]
Воспроизведение:

1. Разлогиниться.
2. Обновить страницу.
3. Авторизоваться. Получится вот такое:
![2015-12-12 14-10-36 freefeed - google chrome](https://cloud.githubusercontent.com/assets/132120/11761696/3cc798da-a0dd-11e5-8d44-b9651723acaf.png)
Обратите внимание на обведённую пустоту.
4. Кликнуть на заголовок, чтобы перейти во френдленту.
5. Кликнуть на поле ввода поста.
6. Кликнуть на Add/Edit
![2015-12-12 14-12-00 freefeed - google chrome](https://cloud.githubusercontent.com/assets/132120/11761698/4e3a4a40-a0dd-11e5-8bef-19e23755e6ea.png)
Если кликнуть на селектор, то в нём покажется ​_только_​ My feed, но и он на самом деле будет недоступен — пост отправить нельзя. И дальше уже ничего не работает, даже переходы по ссылкам, помогает только перезагрузка.

В консоли при этом одна ошибка, вот такая:
![2015-12-12 14-13-40 freefeed - google chrome](https://cloud.githubusercontent.com/assets/132120/11761700/5dac39ca-a0dd-11e5-9a25-e49b6fef5877.png)

**Comment by ujenjt** [comment]
Looks like it has already fixed
