### ISSUE TITLE
Make it easier to discover lists of blocked and hidden users

### ISSUE THREAD

**Issue by n1313** [FreeFeed/freefeed-react-client#1463]
List of hidden users is at https://freefeed.net/settings/appearance. List of blocked users is at https://freefeed.net/friends?show=blocked. I think these two lists are related and it would make sense to have a link between them.

Proposal: add a link to the list of blocked users under the list of hidden users, and add a link to the list of hidden users under the list of blocked users.

**Comment by wetterkrank** [comment]
@n1313, @indeyets, Any of this look ok to you?

Appearance settings (positioning options):
![image](https://user-images.githubusercontent.com/736843/143913072-342cab8c-0704-4faa-bc48-7bf61f9ef619.png)
![image](https://user-images.githubusercontent.com/736843/143913137-9a5960a8-cc37-472d-964f-42d653ed414d.png)

Blocked users list (non-empty and empty list):
![image](https://user-images.githubusercontent.com/736843/143913229-eb1e0d78-9615-4abe-bc5d-cb9b4095b3f2.png)
![image](https://user-images.githubusercontent.com/736843/143913252-1754bd85-8aa8-4ad2-a94d-3b16bb1534cd.png)

(Taking simple tickets to start contributing :)

**Comment by n1313** [comment]
Overall, yes, that's exactly what we need. Thank you! Looking forward to your PR @wetterkrank.

Out of the two options for "go to banned list" link positions, I prefer the second one, where it is a separate line under the form.

Two minor implementation suggestions:
1. I think you can go ahead and add a new heading to Appearance page, like "Hidden users" or something like that, so that you could link directly to it from Banned Users page, e.g. settings/appearance/#hide instead of settings/appearance/#home
2. I think the texts could be massaged a tiny little bit. I would prefer a more neutral action verbs there, "to view a list" instead of "to edit" (I might not want to edit it, and I might not have anything to edit). Similarly, "You can view a list of ..." sounds a bit better to me

Since we're talking about this, maybe we want to streamline the terminology a little bit? "Hide posts from these users or groups" is quite heavy, maybe we could simply say "Hidden users and groups" and add a hint/explanation like "Posts from these (sources? authors? feeds?) will be hidden from your home feed"? /cc @dsumin @davidmz. May be out of scope of this ticket though

**Comment by wetterkrank** [comment]
@n1313 Thanks!
1. Better linking to the list -- makes sense! Can't add a subheading though (we're not using `h5` anywhere else), and looks like the `h4` should come with a `section`. So, I'd group the hide-related settings in this new section then:
![image](https://user-images.githubusercontent.com/736843/144031496-25720539-2836-49ab-98d2-daf7f24c8ba9.png)
As an option, I could just add an anchor for linking directly to the textarea, without making any visual changes. What would be better?

2. Sure, using "view" instead of "edit".

**Comment by n1313** [comment]
I like the heading!
