### ISSUE TITLE
Add my memories 

### ISSUE THREAD

**Issue by Mazafard** [FreeFeed/freefeed-react-client#1468]
It is necessary for some users to review their old posts. It may be possible to accomplish this by adding a box in the sidebar comparable to Memories of {time} (e.g. My memories of {date} ) which calls the API of the user's timeline before a time:

`https://freefeed.net/v2/timelines/{user}?created-before={time}`

<img width="244" alt="Screen Shot 2021-10-29 at 03 08 49" src="https://user-images.githubusercontent.com/2767887/139361871-7d7e6cd0-285b-4530-b53d-36ab6a14d53f.png">

**Comment by Mazafard** [comment]
Based on my review of the code, I found the following route:
https://freefeed.net/{user}/memories/{time}
It appears to solve the first step. Only the UI needs to be changed.

**Comment by davidmz** [comment]
It is also useful to view old posts from another account or group. I am not sure _My_ memories are important enough to show them in every page. Probably we should show “My memories” on my page and @username's memories on their page?

**Comment by Mazafard** [comment]
You made a better suggestion than mine, it seems. I'll modify it to the way you suggested.

**Comment by kukutz** [comment]
@Mazafard friendly reminder :)

**Comment by indeyets** [comment]
implemented via #1523
