### ISSUE TITLE
Upgrade "testing-library/user-event" package

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#1527]
It looks like modern version of `@testing-library/user-event` is not compatible with our tests. We'll need to tweak them at the time of upgrade

https://github.com/testing-library/user-event/releases/tag/v14.0.0

@n1313 would you be able to check this?

**Comment by n1313** [comment]
> APIs always return a Promise.

This sounds like an update of every test. Do we have to upgrade soon? Is there a problem that we have that v14 solves?

**Comment by indeyets** [comment]
@n1313 no rush. it would be nice to avoid situation when we have to upgrade 3 generations up (like we have with socket.io 🤦🏼‍♂️)
