### ISSUE TITLE
Click on the same link should lead to data-refreshing

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#167]
Whenever user clicks on the same url, as the one which is currently loaded nothing happens.

Data-reload should be triggered instead:
- [ ] show throbber
- [ ] execute fetch-request to API
- [ ] handle response in redux

It should be easier to implement this if we migrate to [redux-simple-router](https://github.com/rackt/redux-simple-router) which [has support](https://github.com/rackt/redux-simple-router/pull/40) for such scenarios out of the box.

┆Issue is synchronized with this [Trello card](https://trello.com/c/GA0juyXz)

**Comment by kadmil** [comment]
It's likely be way easier with newer versions on the react-router itself with `onUpdate` hooks. They should also remove the need for complex code for pagination and the like.

**Comment by kadmil** [comment]
redux-simple-router had no good story around hash-history by the time I've looked at, so need another investigation on this.
