### ISSUE TITLE
Confirmation for 'Delete' for your own post (or comment)

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#204]
https://freefeed-product.hackpad.com/Undo--hpmLRzmCa18

After clicking 'delete' link for your own post (or comment) a layer with 'Yes, delete!' and 'Cancel' links appears. After clicking 'Yes, delete!' the entry is deleted. After clicking 'Cancel' the layer disappears, nothing happens.

**Comment by clbn** [comment]
Fixed in #219.
