### ISSUE TITLE
Likes list collapse logic

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#210]
Expected:

- The list of likes under a post should remain expanded unless the amount of likes is less or equal to 4.
- After amount of likes becomes greater than 4, the list should be collapsed.
- Collapsed likes list should contain 3 last likes in reverse chronological order, and "N other people liked this" text (where "N other people" is an expand link; N is always greater than 1).
- If the post is liked by current (authenticated) user, (1) their like should always be displayed in the head of the list; (2) display name should be replaced with "You".

Actual:

- At this moment likes collapse triggers directly after 4th like. So a post with 5 likes has "1 other people liked this".
- Current user like is shown as display name, instead of "You".

Example:

![Alt text](https://monosnap.com/file/ttatMoisiCDNz1AzroLLldnQK7vzW4.png)

**Comment by clbn** [comment]
- After 6th like the list should be collapsed.
- Collapsed likes list should contain 4 last likes
- N is always **greater** than 2

Does not compute.

**Comment by dreikanter** [comment]
Thanks! Changed to "greater than 1".

**Comment by clbn** [comment]
I checked the screenshots of Old FriendFeed. It seems we should decrease values above by one. That is:

- If L <= 4, show all of them
- If L >= 5, show 3 + N collapsed.

**Comment by clbn** [comment]
Examples:

- **Alpha** liked this
- **Alpha** and **Bravo** liked this
- **Alpha**, **Bravo** and **Charlie** liked this
- **Alpha**, **Bravo**, **Charlie** and **Delta** liked this
- **Alpha**, **Bravo**, **Charlie** and **2 other people** liked this
- **Alpha**, **Bravo**, **Charlie** and **3 other people** liked this
- ...

**Comment by dreikanter** [comment]
Updated.

**Comment by clbn** [comment]
@dreikanter Thanks! Hope we'll have time to fix this soon.
