### ISSUE TITLE
Click on the comment cloud retains @username after clicking cancel

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#221]
Reproducing:
1. Navigate to a post.
2. Click on the comment to open a new edit comment box.
3. Click cancel.
4. Click on the same comment again.

The edit comment box would contain: '@username: @username:'

Expected - the edit box contains: '@username: '

**Comment by clbn** [comment]
![image](https://cloud.githubusercontent.com/assets/1071933/12873900/8786102c-cdc9-11e5-835e-2ef4572a4cba.png)
