### ISSUE TITLE
Private groups: select group type on creation

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#226]
https://*.freefeed.net/groups/create:
---
…
username: [   ]

Status: (dropdown)
[ Public group ] (default)
[ Private group ]
---

**Comment by dsumin** [comment]
Dropdown should list:
Public group
Private group
Restricted group (only admins can post)
Private restricted group (only admins can post)

**Comment by dsumin** [comment]
Revised UI:

```
(x) Public group
( ) Private group

[ ] Restricted group (only admin can post)
```

**Comment by berkus** [comment]
Current:
![](https://dl.dropboxusercontent.com/s/5sn49ka3cuspjy9/2016-03-16%20at%2014.27.png)

Consider this fixed.
