### ISSUE TITLE
Private groups: edit group type (admin only)

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#227]
https://*.freefeed.net/groupname/settings

---
...
Update group picture
[ Choose file ] ....

Status: (dropdown)
[ Public group ] 
[ Private group ]

Group description
...
---

**Comment by dsumin** [comment]
Dropdown should list:
Public group
Private group
Restricted group (only admins can post)
Private restricted group (only admins can post)

**Comment by berkus** [comment]
Done.
