### ISSUE TITLE
Groups: Managing subscribers (group admin only)

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#228]
https://freefeed.net/groupname/subscribers
---
Manage subscribers // ссылка на https://freefeed.net/groupname/manage-subscribers

Admin(s)

[ Avatar lists ]

Subscriber(s)

[ Avatar lists ]
----

по ссылке Manage subscribers:
https://freefeed.net/groupname/manage-subscribers
---
Browse subscribers // ссылка на https://freefeed.net/groupname/subscribers

//Аватарки пользователей:
[             ] username
[ Avatar  ] Remove
[             ] Make admin

Admins // Аватарки админов
[             ] username
[ Avatar  ] Remove admin rights
[             ] 
---

**Comment by berkus** [comment]
Dupe of https://dev.freefeed.net/T9
