### ISSUE TITLE
Add settings to control how screen/user names are displayed  

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#255]
Add per-user front-end persistent settings (displayed on https://beta.freefeed.net/settings)
before "Change password" section

```
Screen names:
(*) Show screen names (default)
( ) Show user names
( ) Show user name after screen name

[ ] Show your screen name / user name instead of 'You'.

[ Update ]
```

show user names - shows user names only
Show user name after screen name:  screen name (username)

**Comment by clbn** [comment]
Implemented in #286.
