### ISSUE TITLE
Feed selector is not reset after posting

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#260]
Navigate to https://beta.freefeed.net/
Select a group (i.e. photo) along with My Feed.
Enter text, click Post.

Post appears both in My Feed and @photo, but the feed selector retains My Feed and Photo

Expected behavior: Feed selector is reset to My Feed and hidden.

**Comment by berkus** [comment]
Dupe of https://dev.freefeed.net/T16
