### ISSUE TITLE
Post from private user to public group have lock icon

### ISSUE THREAD

**Issue by davidmz** [FreeFeed/freefeed-react-client#262]
Example: https://george.freefeed.net/test/26044a9a-eac7-48a8-91e7-f0d42bff5149

Pull request https://github.com/FreeFeed/freefeed-react-client/pull/225 uses wrong algorythm. It checks only `isPrivate` property of post's author, but it must check visibility of all post destination's feeds. See ember code: https://github.com/FreeFeed/freefeed-html/blob/development/public%2Fjs%2Fapp%2Fmodels%2FPost.js#L70

**Comment by clbn** [comment]
Right, thanks!

So it's only "private" when all of the recipients are "private". Does it sound right?

**Comment by davidmz** [comment]
Yes, it's correct.

**Comment by clbn** [comment]
I'm sorry I pushed the fix directly to `master`. Here's the screenshot for the unborn pull request:

<img width="737" alt="2016-02-12 22-20-52 lock-unlock-icon" src="https://cloud.githubusercontent.com/assets/1071933/13021022/07108170-d1d9-11e5-8d44-bbfde5f37384.png">
