### ISSUE TITLE
Subscribe is not working for private users

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#264]
Clicking subscribe for a private user (group) should send subscription request

**Comment by davidmz** [comment]
Not only, it must have different text and different behavior (and made a different api call). On classic frontend:

Private account:
![image](https://cloud.githubusercontent.com/assets/132120/12927589/f2a6d524-cf79-11e5-95c8-16ac8ea77f82.png)

Public account:
![image](https://cloud.githubusercontent.com/assets/132120/12927609/0c7fac82-cf7a-11e5-8db9-713cac7608f5.png)
