### ISSUE TITLE
Realtime - comments appear without screen name

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#267]
If a user has registered after the page was opened and starts commenting, the comments appear without screen name.

Console: 
`We've got comment with unknown author with id 6763be22-83f6-4742-8079-83b97550798e`

**Comment by kadmil** [comment]
Must be fixed now, could you tell me, does this reproduce?

**Comment by berkus** [comment]
Dupe of https://dev.freefeed.net/T8
