### ISSUE TITLE
Realtime - post with an attached picture won't appear

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#268]
User dmitrysumin has his home feed open.
User dmitrysumin is subscribed to user1
User user1 creates a post with an attached pictore

This new post won't be displayed in dmitrysumin
The post will be displayed after browser refresh

**Comment by clbn** [comment]
```
Unhandled promise rejection TypeError: Cannot read property 'mediaType' of undefined
```
