### ISSUE TITLE
Show posts' comments

### ISSUE THREAD

**Issue by berkus** [FreeFeed/freefeed-react-client#3]
Take templates from Ember frontend and make comments visible in posts.

The comment editing workflow will be next after this is done.

**Comment by clbn** [comment]
I think it would be a good idea not to "carbon copy" the templates from Ember since the latter are somewhat bloated here and there. So creating simpler (and more "flat") DOM structure seems like a good idea.

**Comment by berkus** [comment]
It would be nice to construct a set of "building blocks" — for example user name could be displayed differently based on several options and I think capturing this in a single <UserNameView> can be helpful.
