### ISSUE TITLE
Request to the private group returns to the user who has sent it

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#311]
(george.freefeed.net)

1. You has a non-private feed;
2. You go to private group and send a request to it;
3. Go to your home page and refresh the cache.

Actual result: you get a request to your feed from that private group, and you can't do anything with it: can't accept, can't reject. (owner of that group get a request too).

Expected result: the owner of the group is the only one who get the request.

**Comment by berkus** [comment]
Dupe of https://dev.freefeed.net/T12
