### ISSUE TITLE
Blue notification «Updated!» on the group settings page doesn't disappear

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#315]
>> Steps: 
1. Change some settings of your group.
2. Go to your feed. 
3. Return to the feed of that group.
4. Go to group's settings page

>> Actual result: 
You still see a blue notification «Updated!» here. 

>> Expected result:
You don't see it.

**Comment by clbn** [comment]
Fixed in #366 (the second commit).
