### ISSUE TITLE
Realtime doesn't work after home page reloading

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#331]
(Chrome Version 48.0.2564.116 m on Windows)

Steps to reproduce: 
1. Open home page. Make sure realtime works.
2. Reload the page

Actual Result: 
Realtime doesn't work, you need to stop it and run it again. 

Expected result: 
Realtime keeps working.

**Comment by kadmil** [comment]
I've done work around this, could you tell me whether this still reproduces or not?

**Comment by govorkaya** [comment]
I can't reproduce it on george.freefeed.net

**Comment by kadmil** [comment]
@berkus, @indeyets what should we do with seems-like-no-reproducible things like this?

**Comment by berkus** [comment]
Dupe of https://dev.freefeed.net/T7
