### ISSUE TITLE
Delete should have an Undo option

### ISSUE THREAD

**Issue by smallq-git** [FreeFeed/freefeed-react-client#34]
When user deletes comment or post, there should be an Undo option.
1. Click Delete on post or comment.
2. Post or comment is replaced with message area.
3. Message area contains information ("Entry deleted"/"Comment deleted") and Undo link.
4. Undo link restores comment or post.

![image](https://cloud.githubusercontent.com/assets/7983303/10351047/1aefce8c-6d50-11e5-882c-b8be9d0415bf.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/pYoCfK3B)

**Comment by berkus** [comment]
Requires backend support.

**Comment by urbansheep** [comment]
Undo message is only visible until view is refreshed. After the feed/post view is reloaded, no “Comment deleted/Entry deleted” should be displayed anymore.
