### ISSUE TITLE
Ban, Comment: Conversation involving banned user is displayed incorrectly

### ISSUE THREAD

**Issue by smallq-git** [FreeFeed/freefeed-react-client#35]
If conversation involves banned user, comments by this user should be treated as non-existing.

Pre-condition: 
1. testuser3 created a post.
2. testuser1 commented on the post.
3. testuser3 banned testuser1.
4. conversation continued until comments are collapsed.

1. Open testuser3's feed.
2. View conversation involving testuser1.

Expected: comment collapse, visible comments, comment updates are happening as if testuser1 and their comments do not exist at all.
Actual: comments number are calculated including testuser1's comments. Comments above and below collapse are either duplicated or empty.

Post viewed by banning user (testuser3):
![image](https://cloud.githubusercontent.com/assets/7983303/10351189/d6219f50-6d50-11e5-9756-24045964afe0.png)

**Comment by berkus** [comment]
There's still case of many last comments by banned user but we cannot fix this in frontend, will be a backend task after postgres.
