### ISSUE TITLE
Relogin from one user to another make you see the list of groups of the first user

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#352]
Steps
1. Log in as a user who is a member of several groups. (ex. govorkaya5 with password ljcz263535).
2. Go to link Browse/edit groups
2. Log out.
3. Log in as a user who is not a member of any group (ex. vinny with pass 2635326353).
3. Go to link Browse/edit groups

Actual result: 
You see a list of groups, same as for first user. After reload of the page the list becomes empty. 

Expected result: 
You don't see any information related to another user.

**Comment by clbn** [comment]
Fixed in #365.
