### ISSUE TITLE
Show posts' likes

### ISSUE THREAD

**Issue by berkus** [FreeFeed/freefeed-react-client#5]
In the same way as with comments, using `<List of <users>>` construct display posts' existing likes.

Likes folding need to be handled (that's `omittedLikes` in old code), some handling in store for when the likes list is expanded - if no more omittedLikes then full list should be displayed instead.

**Comment by smallq-git** [comment]
There should never be "and 1 other people liked this" message. If there are only 4 likers, their names should be listed fully. Likes should only be collapsed if there are 5+ likers, making it "2 other people" at minimum.

![image](https://cloud.githubusercontent.com/assets/7983303/10350553/55e2e022-6d4d-11e5-9d4e-43d0ead87a90.png)

**Comment by berkus** [comment]
Handled in #56
