### ISSUE TITLE
"Like" on your own fresh post

### ISSUE THREAD

**Issue by clbn** [FreeFeed/freefeed-react-client#60]
When user creates a post and then "Likes" it right away (without a page reload), there's no reaction for this (post still looks not-"Liked") and there's an error in console: `Unhandled promise rejection TypeError: Can't call method on  undefined`. If user reloads page, the post becomes "Liked".

I would say we should fix the bug with data model somewhere, but actually we should just remove an option to like your own posts (seriously, guys, that's a perversion).

**Comment by kadmil** [comment]
Fixed in pending pull-request
https://github.com/ujenjt/freefeed-react-client/commit/ab3a981d36b6e81aef194c436a0d5f82d5da160f#diff-e3c8ead83682f4ee4a4303e634042ab1R350

**Comment by clbn** [comment]
@kadmil I still think we have to remove an option to like your own posts.

Ping @berkus @indeyets @urbansheep.

**Comment by berkus** [comment]
Liking your own post is supported by default. This ticket is not about changing this behavior.

File another ticket and discuss with @urbansheep.

**Comment by berkus** [comment]
Closing this, fix is applied, regarding removing this functionality discuss elsewhere please.
