### ISSUE TITLE
Show unread directs counter on top of mobile screen

### ISSUE THREAD

**Issue by xekc** [FreeFeed/freefeed-react-client#663]
Now you need to scroll down, on the very bottom of the screen, to see an unread directs counter on your phone. Though we have menu item "Direct messages" in header, let's add direct counter there.

![preview-directs_mobile-2](https://user-images.githubusercontent.com/1575753/30299807-59fcc0b0-9749-11e7-8987-1a298670c381.png)
![preview-directs_mobile](https://user-images.githubusercontent.com/1575753/30299806-59fbd754-9749-11e7-9ee8-2aa1223b14c0.png)

Via: https://dev.freefeed.net/T108

**Comment by dsumin** [comment]
This has already been fixed.
