### ISSUE TITLE
Create component for user display

### ISSUE THREAD

**Issue by berkus** [FreeFeed/freefeed-react-client#7]
надо сделать наверное компонентик UserNameInfo или как-то так и отображать его по-разному в зависимости от настроек  пользователя (если помните обсуждали перенос опций из беттерфида, это вот про оно)
то есть юзер у нас может на странице отображаться как
- только displayname
- только username
- `displayname (username)` а-ля https://dl.dropboxusercontent.com/s/vv9d2ghll5gfnyl/2015-09-28%20at%2022.45.png (11KB)

логично что хотелось бы это в один компонент вынести и потом переиспользовать везде где нужно (а это нужно в заголовках постов, комментах, лайках…)

также bf умеет по ховеру показывать попап для этого пользователя - возможно его стоит генерировать в этом же компоненте?

**Comment by kadmil** [comment]
Эта штука должна работать как в bf всегда? Или мы будем ее включать-выключать?

**Comment by berkus** [comment]
Какая именно штука?

**Comment by kadmil** [comment]
Попап "как в bf"

**Comment by berkus** [comment]
Сейчас на попап можно не обращать внимания, просто иметь в виду. Он будет показываться всегда на десктопе, но не на мобиле.

**Comment by kadmil** [comment]
Понял
