### ISSUE TITLE
Search displays posts of users that have banned you

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#739]
User A bans user B.
User A makes a post 'bantest'
User B searches for 'bantest'

'bantest' post of user A is displayed.

expected behavior: 'bantest' post of user A should not be displayed.

┆Issue is synchronized with this [Trello card](https://trello.com/c/twS6mjKP)

**Comment by davidmz** [comment]
This issue was moved to FreeFeed/freefeed-server#260
