### ISSUE TITLE
По ссылке https://freefeed.net/<username>/comments не показываются группы

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#762]
1. Пользователь @dsumin откомментировал пост A в группе group и пост B в своем фиде.
2. Если открыть ссылку https://freefeed.net/dsumin/comments, то будут показаны посты A и B, но у поста A не будет указано, что он в группу group.

Ожидаемое поведение: у поста A будет указано, что он в группу group. (так же, как в discussions).

┆Issue is synchronized with this [Trello card](https://trello.com/c/TLu1DaHr)

**Comment by ofkindness** [comment]
Выглядит не как баг, а скорее как неопределенное поведение. Отображение групп в постах выключается (так же как и в самом фиде самого пользователя) флагом isInUserFeed
Проверку убрал в https://github.com/FreeFeed/freefeed-react-client/pull/767 группы теперь показываются, мне кажется данный вопрос нуждается в дополнительном обсуждении: 
- если подобное поведение не нужно, стоит убрать флаг `isInUserFeed` совсем
- если оно для чего-то нужно придется разделить (доработать) код отображения userFeed в случае показа самого пользовательского фида и показа `username/comments`

В силу небольшого опыта мне самому непросто принять какое-нибудь из этих решений
