### ISSUE TITLE
Sign-in requires clicking on Sign In button twice

### ISSUE THREAD

**Issue by ghost** [FreeFeed/freefeed-react-client#769]
OS: Windows 7
Browser: Chrome 65.0.3325.181 (64-bit)

Steps to reproduce: 
1. open https://freefeed.net in incognito mode. 
2. provide valid credentials
3. push "Sign in" button

Expected result: 
You get logged in and you see your home page. 

Actual Result: 
You still see the same form. To get to home page, you need either click on the "Sign in" button one more time or reload the page.

┆Issue is synchronized with this [Trello card](https://trello.com/c/WHgNpm93)

**Comment by dsumin** [comment]
Unable to reproduce. 

Browser/OS?

**Comment by ghost** [comment]
@dsumin also can't reproduce now.
