### ISSUE TITLE
Post Editor

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#77]
The goal is to implement a form to be used for post authoring and editing. UI behaviour description will follow.

> There are two implementation priority levels: **Must have** (first priority, which is default), and **Want to have** (second priority). If priority level is not defined for specific section or requirement, it should be assumed as **Must have.**
## 

**Inactive form state**

![Alt text](https://monosnap.com/file/nyHJK1BwQ1ElHNuw5n8OnUdoDnxT2D.png)
1. After initial page load the form should remain in an _inactive_ state.
2. In this state the form should have a reduced set of visible elements, that include (1) current user avatar and (2) post body text area only.
## 

**Active form state**

![Alt text](https://monosnap.com/file/Y52PdXFBXEsXvFwYwc1D6aekkpwCy2.png)
1. After the body text area get the focus, form state changes from _inactive_ to _active._
2. Visible elements: (1) _To_ field, (2) New comment placeholder, (3) Preview button, and (4) Post button.
3. During _inactive-to-active_ transition, body and avatar absolute position should remain unchanged (should not be pushed down by _To_ field).
4. If an _empty_ post editor form looses focus, it should "collapse" back from _active_ to _inactive_ state.
   - A post editor is _empty_ if there are no content in _To_ and body fields, and the number of comments is zero.
   - "Loosing focus" means here that the user moved in-page focus outside from the form components.
## 

**To field**

![Alt text](https://monosnap.com/file/FE9HXGZImHnIiVBBpOy0TcFhr4z7pB.png)
1. _To_ field is a one-line tokenized text input ([example](http://loopj.com/jquery-tokeninput/)).
2. Default content for _To_ is "My Feed", which is primary feed for current user feed.
3. It should be possible to add any number of items to _To_.
4. It should be possible to delete any item from _To_ field.
5. Empty state is _not valid_ for _To_ (the user should be able to publish a post only if there are zero non-valid fields).
6. _To_ field state is also not valid when it contains unknown or invalid name.
7. _To_ should have suggestion dropdown, based on current user subscriptions list.
8. "Post" button should remain disabled if there are more than zero non-valid fields.
## 

**Writing post and comments**

![Alt text](https://monosnap.com/file/CXHtEpk96hoSXFKMDrbPsFthPhNxcd.png)
1. Body text area height should follow content size. Text area should automatically stretch/shrink so the body text will be visible w/o scrolling ([example](http://www.jacklmoore.com/autosize/)).
2. Minimum height of body text area should be equals to the avatar height.
## 

**New comment placeholder**

![Alt text](https://monosnap.com/file/ELBSmIOO1xRqKDsukMnqAqOOC0sUvI.png)
1. The purpose of the NCP is to inform the user that there is a possibility to add a comment block after the post body.
2. The placeholder should look identically to a comment text area, but remain inactive until focused. Inactive state should tell the user "I'm here, if you need me, but no probs, if you don't".
3. Inactive placeholder state should be visually distinguishable from disabled control. Comment field is _optional,_ but not _unavailable._
4. After user click the placeholder, it should switch to active state.
5. If the last comment text area looses focus, it turns back to a inactive placeholder unless it is not empty. This transition should trigger only for the last comment.
6. New NCP should appear below focused text area of the last comment, after user start typing.
7. Post editor should not contain more than one NCP, and the placeholder should always be in the bottom of comments list.
8. Minimum height of comment text area is 1 line (same as `<input type=text>`).
## 

**Writing comments**

![Alt text](https://monosnap.com/file/7xNtzsKzdssRvXE47ANPILcbncmn1t.png)
1. Comment text area should behave identically to the body text area (stretch/shrink to follow content size, so all comment lines are visible w/o scrolling).
2. The user should be able to add any number of comments during new post creation.
3. If the post editor form is submitted with empty comments, those ones should be ignored. Non-empty comments should appear under the published post, remaining the original order.
4. It should be possible to start a new comment by pressing `Ctrl-Enter` (`Cmd-Enter` on Mac) while editing post body, or another existing comment. The new comment text area should appear correspondingly below the post body, or below the focused comment.
## 

**Managing comments**
1. Each comment should have _Delete_ icons next to top-left corner of the text area.
2. Delete = [x-icon](http://fortawesome.github.io/Font-Awesome/icon/times/).

_Want to have:_
1. Each comment should have _Reorder_ icons next to top-left corner of the text area (vertical order is Reorder, Delete).
2. Reorder = [sandwich icon](http://fortawesome.github.io/Font-Awesome/icon/bars/).
3. If the comments sequence contain 2+ items, the user should be able to reorder it by dragging Reorder icons. (Example: see _Drag handle and selectable text_ section [here](http://rubaxa.github.io/Sortable/))
## 

**Deleting comments**
1. _Delete_ icon should delete comment w/o confirmation prompt.

_Want to have:_
1. After deletion a comment should collapse to a _Deleted Comment Placeholder._
2. After the user deletes an empty comment text area, it should just disappear, with no DCP.
3. If the user clicks _Undo_ link inside DCP, the comment should appear back on its place.
4. If the post editor form containing DCPs was submitted, deleted comments should (obviously) not appear in the comments list under the published post.
5. the user should be able to permanently delete comment by a click on the X-icon on DCP. After permanent deletion, DCP should disappear (the comment could not be restored after this action).

![Alt text](https://monosnap.com/file/EjGFyyV5FjzrLOa4arUnvqz2pzaB80.png)
## 

**Attaching files**

![Alt text](https://monosnap.com/file/PyAf5pQLdXfOLeEb2oVlICi1s50nII.png)
1. The user should be able to attach a file by dropping it anywhere on the form (example: [Disqus](https://disqus.com) new comment form).
2. Alternative way to attach a file is by clicking _Attach_ button (file browsing dialog should appear).
3. After the user attaches an image file, a preview should appear below the post body.
4. Image preview should be scaled to standard height. If preview width exceeds maximum width limit, it should be cropped (for example, 1000×10px image attachment should not break the layout).
5. User should be able to attach multiple files at once, either by dropping them on the form, or selecting from the browsing dialog.
6. It should be possible to delete any attached image by clicking X-icon in top right corner of each image.

![Alt text](https://monosnap.com/file/tKc2J8ERwEgvb3zHN2UTHrT0UqW8uq.png)
1. Non-image attachments should appear below image previews (if there are any).
2. User should be able to delete an attachment by clicking X-icon next to the file name.

_Want to have:_
1. It should be possible to change images order by dragging previews ([example](http://rubaxa.github.io/Sortable/)).
## 

**Distraction free mode** _(Want to have)_

![Alt text](https://monosnap.com/file/Zd8tVRzw4uV272sgoDHCOPp2wualcA.png)
1. Post body text area should contain an _full screen_ icon to switch to Distraction Free Mode.
2. In DFM the post editor should be the only visible element on page.
3. In DFM post editor itself should look behave same way as in normal mode.
4. Id DFM _full screen_ icon should be replaced by _exit full screen_ icon.
5. It should be possible to exit DFM by clicking an icon, or pressing `Esc`.
## 

**Auto save** _(Want to have)_
1. The post content should be dynamically saved.
2. If network connection is lost, the post should be persisted on client side (in Local Storage).
3. The form content should "survive" if the user close browser window (form state should be automatically restored after the page will be reopened).
4. It is obviously not possible to guarantee user data will be safe after browser crash, but the amount of lost changes should be reasonably minimized in this case.
## 

**Preview** _(Want to have)_

![Alt text](https://monosnap.com/file/WUFdwJ4CKxyS4utgysC5EbgFcgMSBK.png)
1. The user should be able to preview the post before publishing it.
2. In preview mode the post (including comments thread and attachments) should be represented the same way it suppose to look after publishing.
3. _Preview_ button should be replaced with **Continue editing.**
4. _Post_ button should remain available, so the user could publish the post directly from preview.
## 

**Publishing a post**
1. After user click _Post_ button, the new post (including attachments and comments) should appear in specified feeds.
## 

**Editing a published post**
1. User should be able to edit a published post.
2. In this case the post editor should behave identical to new post creation mode, with few exceptions: 
   1. Comment posting for a published post is independent from editing post body (comment and post body should be edited via separate forms, and be separately submitted).
   2. It should be not possible to reorder existing comments after post was published in the first time.
3. It should be still possible to edit _To_ field by adding/removing user or group feed names.
4. If the user changed _To_ content during post editing, the post visibility should change.
## 

**Violating other people privacy**

![Alt text](https://monosnap.com/file/zheH8n83983St39S7iEKy5pQTiSy3O.png)
1. If (1) a post was initially published in a private feed, (2) there are likes/comments from other users, and (3) the post owner adds a public feed to the _To_ field during post editing, a _non-modal_ notification should appear: "Warning: Publishing this post may violate other users privacy."
2. In this case _Post_ button should remain disabled until "I know what I'm doing." checkbox is checked by the user.

**Comment by dreikanter** [comment]
Attn @urbansheep

**Comment by dreikanter** [comment]
Would be cool to have in Betterfeed:

**Words counter**

![Alt text](https://monosnap.com/file/IHw3NLnYD2VHiOeSjZJbAQc0lU7J6g.png)

1. There should be a words counter below the post editor.
1. The counter should display total amount of words in the post body and comments.
1. Words counter should appear and dynamically update when user types.
1. Words counter should not be visible when the form is empty.
1. Words counter is a part of the editor, *not* the published content.

**Comment by berkus** [comment]
No need to betterfeed it, can be part of react editor form easily.

**Comment by dreikanter** [comment]
@berkus I've moved this one outside spec after discussing with @urbansheep. I think it could be implemented as an optional/experimental feature to see if someone find it useful (besides me).

**Comment by davidmz** [comment]
User also should be able to reorder attached files by drag'n'drop.

**Comment by berkus** [comment]
It *is* useful and besides very easy to implement. We can add option to hide it for those who don't need it.

For react frontend assume we don't have/use betterfeed.

**Comment by clbn** [comment]
Nice-looking interface, great work.

> the user should be able to reorder it by dragging Reorder icons

BTW, the only reason we don't have it in our current attachment interface is the data structure we use in Redis (there's no info on order). So in the next (or current, why not) backend we need this property. Alternatively, data structure of attachments list should support it naturally, like if it is an ordered array, not an unordered set.
