### ISSUE TITLE
Realtime comment appears out of place

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#779]
The last comment Realtime comment appears as the first one:
![image](https://user-images.githubusercontent.com/2417937/39093520-7a509a6e-4629-11e8-838a-9fb1b4537be0.png)

Should be the last one:
![image](https://user-images.githubusercontent.com/2417937/39093525-86cff5dc-4629-11e8-8875-d3207b78e3ec.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/PzmFjiYV)

**Comment by davidmz** [comment]
How to reproduce it?

**Comment by kadmil** [comment]
Should be something more complex; straightforward commenting on the post doesn't lead to the situation. Note, that this could have something to do with comment folding code, but I wasn't able to break the thing.
