### ISSUE TITLE
Comment disappears while editing

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#780]
User creates a post.
Clicks a link to open this post's page.
User posts a "test" comment.
User clicks edit comment and revises comment's text to "test 1" and clicks [ comment button ]
User clicks edit comment.

Now: comment is empty.

Expected: comment is "test 1".

┆Issue is synchronized with this [Trello card](https://trello.com/c/j9c2tQmN)

**Comment by n1313** [comment]
See also https://github.com/FreeFeed/freefeed-react-client/issues/753
