### ISSUE TITLE
No rule to make target 'prod'

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-react-client#786]
Hello,
I get this error when I run `make prod` (which is indicated in the docs). How can I fix this and make a production ready package?

┆Issue is synchronized with this [Trello card](https://trello.com/c/W7dDJg2n)

**Comment by indeyets** [comment]
the target is [definitely present](https://github.com/FreeFeed/freefeed-react-client/blob/stable/Makefile#L9)
