### ISSUE TITLE
How to change moment.js default language?

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-react-client#788]
Hello,

When I change the language in `index.js` to `html(lang='fr')`, the moment strings still appear in English. 
I'm wondering how can I change this?

┆Issue is synchronized with this [Trello card](https://trello.com/c/qdMvl9Oa)

**Comment by dsumin** [comment]
moment.locale("fr")?

**Comment by k0fi** [comment]
Where should I put it? When I put `moment.locale("fr");` after import statements in `time-display.jsx` nothing is changed. I have also tried it inside `render() {}`.

**Comment by indeyets** [comment]
There's no straight-forward way to do that, unfortunately. Localization is pretty-much absent/hardcoded
