### ISSUE TITLE
How to translate 'more comments'?

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-react-client#789]
Hi,
I'm going to translate `'more comments'` string below posts but could not find it anywhere. 
Appreciate your hint on how to replace it.

┆Issue is synchronized with this [Trello card](https://trello.com/c/jPCRilz4)

**Comment by dsumin** [comment]
https://github.com/FreeFeed/freefeed-react-client/blob/stable/src/components/more-comments-wrapper.jsx?
