### ISSUE TITLE
Comment's text area should get focused after Edit is selected 

### ISSUE THREAD

**Issue by ghost** [FreeFeed/freefeed-react-client#790]
**OS:** iOS 10.11.6, Google Chrome 66.0.3359.139
**Frontend**: React frontend freefeed.net 

**Steps to reproduce**:
1. Open any post in a separate tab (e.g. https://freefeed.net/asdfasdf/b0b31ed9-d009-442c-9545-8c34dc553dd7) 
2. Add a comment.
3. Select "Edit" link near the comment. 

**Expected result**: 
Comment's text area should automatically get focused. 

**Actual result**: 
Focus is not on the comment's text area.

┆Issue is synchronized with this [Trello card](https://trello.com/c/r7FW7KG7)

**Comment by davidmz** [comment]
Looks like it's fixed.
