### ISSUE TITLE
all the links in emails are obsessively underlined :) 

### ISSUE THREAD

**Issue by chalumnae** [FreeFeed/freefeed-react-client#797]
1. IOS 11 and Android 7 with all the updates installed, mail clients are the built-in Mail on IOS and myMail 6.9 on Android. 
2. DailyBest mailing list
3. Opened the mail
4. URLs are of the same style as on web
5. URLs are all underlined.

┆Issue is synchronized with this [Trello card](https://trello.com/c/ljZjSJzc)

**Comment by chalumnae** [comment]
Don't see an option to attach screenshots, but here you are: https://tinypic.pl/mdn8h76ff3lb, https://tinypic.pl/a3z1t656l43f

**Comment by dsumin** [comment]
@chalumnae FYI: you can attach an image bu pasting from the clipboard.

**Comment by dsumin** [comment]
Resolved.
