### ISSUE TITLE
Best of day: Unnecessary URL encoding

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#800]
1. Browser-agnostic behavior. Detected on macOS, Chrome (latest, stable).
2. Best of day mailing list
3. Received and opened the email
4. Expected: Link will look identical to web UI. Non-English characters will be displayed in readable form, w/o URL encoding.
5. Actual: URL with some Russian text is encoded.

Sample Wikipedia link that look like this on freefeed.net:

```
https://ru.wikipedia.org/wiki/Уничтожение_воробьёв
```

turns to this in mailing list body:

```
https://ru.wikipedia.org/wiki/%D0%A3%D0%BD%D0%B8%D1%87%D1%82%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2%D0%BE%D1%80%D0%BE%D0%B1%D1%8C%D1%91%D0%B2
```

(No screenshot due to privacy settings of the user account.)

┆Issue is synchronized with this [Trello card](https://trello.com/c/kSKtetpQ)

**Comment by dsumin** [comment]
Works okay now.
