### ISSUE TITLE
Best of day: Hashtags are not linked

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#802]
1. Browser-agnostic behavior. Detected on macOS, Chrome (latest, stable).
2. Best of day mailing list.
3. Received and opened the email.
4. Expected: Hash tags are linked to https://freefeed.net/search?qs=...
5. Actual: Hash tags are not linked.

![image](https://user-images.githubusercontent.com/126636/41190001-71e3535e-6bdf-11e8-8011-dcb6f87be342.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/8XmbTLYU)

**Comment by dsumin** [comment]
Works now.
