### ISSUE TITLE
Best of day: User names are not linked

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#803]
1. Browser-agnostic behavior. Detected on macOS, Chrome (latest, stable).
2. Best of day mailing list.
3. Received and opened the email.
4. Expected: Each @-username instance within comment body is linked to corresponding user home feed, same way as in web UI. (Can't tell if same is true for post contents, neither of posts I've seen so far has user mentions.)
5. Actual: User names are not linked.

![image](https://user-images.githubusercontent.com/126636/41201365-2f58e14e-6cbf-11e8-8f2a-d9731002d015.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/ctABJ7y1)

**Comment by dsumin** [comment]
Fixed.
