### ISSUE TITLE
Best of day: Some icons are not loaded

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#804]
1. Gmail web app, Chrome (latest, stable), macOS. Gmail app on Android.
2. Best of day mailing list.
3. Received and opened the email.
4. Expected: Post status and comment icons should look identical to Freefeed web UI.
5. Actual: Some icons are not loaded properly. I've tried to purge cache, use different ISP and enable VPN. No effect.

![image](https://user-images.githubusercontent.com/126636/41224146-680af882-6d74-11e8-9ea7-8788a1045e21.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/iLt9uQlw)

**Comment by dsumin** [comment]
Works okay now.
