### ISSUE TITLE
Best of day: Excessive whitespace under each image

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#806]
1. Browser-agnostic behavior. Reproduced in Chrome and Firefox on macOS. As well as Gmail app on Android.
2. Best of day mailing list.
3. Received and opened the email.
4. Expected: Image look should be identical to web UI (1px padding + 1px border from each side of the picture).
5. Actual: Excessive padding on the bottom side of each attached image.

![image](https://user-images.githubusercontent.com/126636/41341956-ba3d6c44-6f03-11e8-866f-bb28b0f1b43c.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/BhczYnoK)

**Comment by dsumin** [comment]
Works okay now.
