### ISSUE TITLE
Best of day: Attached inline images (icons) have wrong size in OSX Mail client

### ISSUE THREAD

**Issue by ArtyomPetrenko** [FreeFeed/freefeed-react-client#807]
Environment: macOS 10.13.4

Attached inline images (icons) have wrong size in OSX Mail client and look too big, see screenshot.

Most probably it is the same issue https://github.com/FreeFeed/freefeed-react-client/issues/804

![2018-06-14_12-18-30](https://user-images.githubusercontent.com/11991340/41403748-4bed6f3e-6fce-11e8-9f88-b612718dc676.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/sZb5a3K0)

**Comment by dsumin** [comment]
Works okay now.

**Comment by ArtyomPetrenko** [comment]
tested - fixed.
