### ISSUE TITLE
Best of day: Posts from hidden groups are shown in message

### ISSUE THREAD

**Issue by ArtyomPetrenko** [FreeFeed/freefeed-react-client#808]
Best of Day message includes posts from groups which are hidden.
Screenshot is attached. 

![2018-06-14_12-36-04](https://user-images.githubusercontent.com/11991340/41404332-9c03fd48-6fcf-11e8-90ad-32dd36e9c5e6.png)
![2018-06-14_12-34-04](https://user-images.githubusercontent.com/11991340/41404340-a0ff8c86-6fcf-11e8-9c34-7cfdebdd47a3.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/1DcoGL84)

**Comment by dsumin** [comment]
Do you see posts from this (or similar) groups in https://freefeed.net/summary/1 ?

**Comment by davidmz** [comment]
“Show/Hide posts” is a client-only feature for now.

**Comment by ArtyomPetrenko** [comment]
@dsumin yes I do. Tested right now by hiding user's posts (desktop Chrome):

![2018-06-14_13-14-30](https://user-images.githubusercontent.com/11991340/41406462-2280282e-6fd5-11e8-9617-8797fe2a04d1.png)

**Comment by dsumin** [comment]
Ok, we might need to implement server-side hide, but this is not a "best of" digest email related issue.

Thank you for reporting it anyways.
