### ISSUE TITLE
Invites: \n in user descriptions

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#829]
suggest @davidmz as invited user.

line breaks in user description are removed, should be replaced with ', ':
![image](https://user-images.githubusercontent.com/2417937/44991013-86bb1780-af9b-11e8-95d4-117c12194944.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/2b0U0Y4r)

**Comment by davidmz** [comment]
Может быть лучше обрезать всё после первого \n? И даже дополнительно добавить ограничение по длине.

**Comment by dsumin** [comment]
Да, согласен. Можно обрезать до первого \n

**Comment by kadmil** [comment]
Fixed in new pull commit
