### ISSUE TITLE
Invites: removing suggested user does not remove the text

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#830]
Suggest: dsumin, indeyets, iceaxe

Remove indeyets from suggested users

Personal message remains the same.

Expected: a line that starts with '@indeyets' is removed from the personal message

┆Issue is synchronized with this [Trello card](https://trello.com/c/kOUHVTM9)

**Comment by kadmil** [comment]
Couldn't reproduce in chrome and safari on Mac

**Comment by dsumin** [comment]
Fixed after https://github.com/FreeFeed/freefeed-react-client/issues/831 got resolved.
