### ISSUE TITLE
Invites: reload breaks the page

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#831]
Go to the https://george.freefeed.net/invite page

Add a few suggested users

Press reload

Try typing 'da' to add davidmz. 'No results found' is displayed. 

Expected: davidmz is displayed in the dropdown.

┆Issue is synchronized with this [Trello card](https://trello.com/c/Z95mQstW)

**Comment by kadmil** [comment]
Resolved in new pull commit

**Comment by dsumin** [comment]
Works now.
