### ISSUE TITLE
Invites: created link

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#832]
I suggest that we show the invitation link created either on a new page (or we might hide all the forms above the link).
---
Invitation link: https://george.freefeed.net/invited/xxxx [ clipboard icon ]
---

Click on the clipboard icon copies the link to the clipboard.

┆Issue is synchronized with this [Trello card](https://trello.com/c/zzfGQOZv)

**Comment by kadmil** [comment]
Added `target="_blank"` in new pull commit; this should make link open in next tab
