### ISSUE TITLE
Invites: english version landing

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#833]
[x] Subscribe to proposed users and groups => Subscribe to recommended users and groups

Please copy text from the "Invite To FreeFeed Page" document, including "Welcome to FreeFeed!" page title, etc.

┆Issue is synchronized with this [Trello card](https://trello.com/c/AJ52PKHo)

**Comment by kadmil** [comment]
Thing with username hint (at least 3 characters) breaks layout on mobile — it adds extra line for label; could we go without it?
