### ISSUE TITLE
Invites: Editing of the Personal message makes radiobuttons work wrong

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#836]
* Windows 8.1 Enterprise, Chrome Version 69.0.3497.81 (Official Build) (64-bit), Desktop
* candy.freefeed.net

**Steps to reproduce:** 
1. log into candy.freefeed.net
2. open https://candy.freefeed.net/invite.
3. Write your own text instead of the user description.
4. change the invitation page language (from russian to english)

Expected result: 
Phrase "Вот интересные пользователи" will be replaced with english analogue, and the description you added will stay unchanged. 

Actual result: 
Phrase "Вот интересные пользователи" and your own description stays unchanged; an extra piece of text appears below: 
![image](https://user-images.githubusercontent.com/41488816/45205872-2aeada00-b28c-11e8-9bad-4b4555cedc75.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/TAM6wEeV)

**Comment by dsumin** [comment]
works now.
