### ISSUE TITLE
Invites: Inaccurate layout 

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#844]
1. macOS ver 10.13.6, Chrome 69.0.3497.81 and Safari 11.1.2
2. Freefed.net
3. How to reproduce: 
Open the invite (e.g. https://freefeed.net/invited/1804f2a7-11a8-4337-a8f9-66732ef58a29) , make the window full-screen. 
4. What was expected: the message text occupies all available space on the screen. 
5. What happens: the message text occupies half of the available width. 
<img width="1235" alt="screen shot 2018-09-16 at 16 44 39" src="https://user-images.githubusercontent.com/41488816/45597193-ecae9280-b9d0-11e8-8c7a-618b7f1c9c50.png">

┆Issue is synchronized with this [Trello card](https://trello.com/c/Bijf0Hrg)

**Comment by nstawski** [comment]
@govorkaya похоже кто-то уже пофиксил эту проблему, как можно поменять статус у тикета?

**Comment by govorkaya** [comment]
@nstawski закрыла, спасибо.
