### ISSUE TITLE
Text changes are lost if image is added in same editing operation.

### ISSUE THREAD

**Issue by blacklion** [FreeFeed/freefeed-react-client#848]
1. Mobile Chrome on Android 8.1
2. freefed.net 1.51.0
3. Create post without attaches. Select "More|Edit". Change text & Attach image. Click "Update".
4. New text & attach are saved.
5. Only attach is saved, but text remains old (pre-edit).

┆Issue is synchronized with this [Trello card](https://trello.com/c/6KQNXa4r)

**Comment by dsumin** [comment]
I can repro this on iPad / Chrome.
