### ISSUE TITLE
Feed settings control issues on mobile devices

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#877]
On an iPad there is no way for me to close the "..." menu:

1. Open home feed.
2. Click "..."
3. Click on Realtime updates

Expected behavior: Realtime updates toggles, menu disappears.

Now: Realtime updates toggles, menu is still displayed

I think that Facebook has a good UI element that could be used as an example of expected behavior:
![image](https://user-images.githubusercontent.com/2417937/49752922-7dd49300-fcba-11e8-8653-8129cff6fb9d.png)

**Comment by davidmz** [comment]
Is this issue still actual?
