### ISSUE TITLE
Other users' realtime comments reset my textarea

### ISSUE THREAD

**Issue by clbn** [FreeFeed/freefeed-react-client#899]
### Repro steps:

1. Open two browser windows.

2. "You": window A with `freefeed.net` and user Alfa.

3. "The other user": window B with `gamma.freefeed.net` and user Beta (you can use any Frf client here; if you prefer freefeed.net, just open it with a different browser or a different browser profile).

4. On homepage in window A, user Alfa click "N more comments" for any post with 4+ comments.

5. User Alfa posts a comment to that post. Then she clicks "edit" and adds some text to her comment, but doesn't submit the form yet.

6. In window B, user Beta posts a comment to the same post.

7. In window A, newly-typed text by user Alfa disappears from the textarea. User Alfa gets upset.

### Screencast:

https://youtu.be/ZLSl9IElTv4

**Comment by davidmz** [comment]
Воспроизводится и с одним и тем же клиентом/юзером в двух окнах.

**Comment by davidmz** [comment]
Более простой способ.
1. Открыть пост с двумя и более комментами (последний - ваш). 
2. Начать редактировать последний. 
3. Не применяя изменения, добавить ещё один коммент. Изменения в редактируемом сотрутся.
