### ISSUE TITLE
Double-search kills react app

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#918]
1. Open https://freefeed.net
2. put "from:indeyets foo" in a search input, press enter. wait for results
3. put "from:indeyets bar" in a search input, press enter

Expected: search-results are displayed
Actual result: Viewport is absolutely white, console says `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

**Comment by indeyets** [comment]
@nstawski можешь на этот посмотреть?

**Comment by nstawski** [comment]
@indeyets да. Можешь меня добавить к этому таску?

**Comment by indeyets** [comment]
я тебя пригласил в организацию. подтверди приглашение и тогда смогу (да ты тогда и сама сможешь себя assign'ить)

**Comment by indeyets** [comment]
С другой стороны, на https://candy.freefeed.net оно не воспроизводится. возможно случайно исправили 🤔

**Comment by davidmz** [comment]
Нет, не исправили. Просто на кенди девелоперская сборка.

**Comment by nstawski** [comment]
Ок, я посмотрю вечером

**Comment by nstawski** [comment]
У меня не получается повторить ни на локальном с candy-бэкендом, ни на freefeed.net

**Comment by davidmz** [comment]
У меня воспроизводится только с включённым BetterFeed, конкретно с модулем висящей пунктуации. Видимо, дело в БФ, а не в клиенте.

**Comment by nstawski** [comment]
Ок, закрываю пока тогда.
