### ISSUE TITLE
Cannot create "protected" group

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#919]
It is not possible to create a protected group.

1. go to https://candy.freefeed.net/groups/create
2. try to select "FreeFeed users (protected group)"

Expected result: it is selected
Actual result: selection shifts to "Everyone (public group)"

**Comment by davidmz** [comment]
Интересно, что группа-то при этом создаётся правильная, protected. Я думаю, это мой баг, я это место писал.
