### ISSUE TITLE
Add sort options to https://freefeed.net/friends page

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#926]
I suggest to add sort options to Friends and Subscriptions sections of https://freefeed.net/friends

Ordered by: date they subscribed (most recent first), username, display name

Please refer to https://gamma.freefeed.net/people, https://github.com/clbn/freefeed-gamma/

**Comment by fetsh-legacy** [comment]
Add this sort options to https://freefeed.net/groups also.

**Comment by dsumin** [comment]
Resolved with lists.
