### ISSUE TITLE
Upgrade raven to 3.27

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#963]
We use outdated Raven-JS (Sentry) library. Should update to latest: https://cdn.ravenjs.com/3.27.0/raven.min.js

Alternative is to switch to 5.x, but that is a more complicated step

**Comment by davidmz** [comment]
Хорошо бы заодно добавить логирование событий redux.

**Comment by indeyets** [comment]
@davidmz событий или ошибок? Поясни

**Comment by davidmz** [comment]
Actions в качестве breadcrumbs при ошибках. См. https://blog.sentry.io/2016/08/24/redux-middleware-error-logging, https://www.npmjs.com/package/redux-sentry-middleware

**Comment by indeyets** [comment]
Вынес дополнения в #968
