### ISSUE TITLE
Chrome browser spelling extension "Sapling Grammar Checker" incompatibility (can't post or comment)

### ISSUE THREAD

**Issue by xekc** [FreeFeed/freefeed-react-client#987]
1. Mac OS / Chrome 76 
2. FreeFeed 1.67.4 (Aug, 21, 2019)
3. Adding https://chrome.google.com/webstore/detail/sapling-grammar-checker-a/pjpgohokimaldkikgejifibjdpbopfdc extension to Chrome breaks text input in new post and comment textareas.
4. Text entry expected to be operational when spelling check extension is enabled.
5. New post and comment fields don't react on text entry. Fields in "Settings" screen work as expected. 

![FreeFeed 2019-08-27 15-12-31](https://user-images.githubusercontent.com/1575753/63779072-d8139380-c8dd-11e9-9fb0-514c6ec7b1da.png)

**Comment by davidmz** [comment]
Bug is reproducing, but it is not clear what exactly is conflicting with our code there. As a workaround I suggest to disable this extension on the freefeed.net domain (it is possible in extension settings).

**Comment by dsumin** [comment]
Won't fix: https://www.screencast.com/t/jNEbkSjzQp6g
